- name: Installing base packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mc

- name: Iptables
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 8080
    jump: ACCEPT